# JdbcTemplate Query Logging
logging:
  file:
    path: /var/logs
    name: TacoCloud.log
  level:
    root: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.hibernate.type: trace
    org.springframework.security: debug

spring:
  config:
    activate:
      on-profile: prod