# JdbcTemplate Query Logging
logging:
  file:
    path: /var/logs
    name: TacoCloud.log
  level:
    root: warn
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.hibernate.type: trace
    org.springframework.security: debug

spring:
  profiles: prod